//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatarzynaKrawczykLab6Zad1.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public string Album { get; set; }
        public Nullable<decimal> FirstTestPoints { get; set; }
        public Nullable<decimal> SecondTestPoints { get; set; }
        public Nullable<decimal> FinalGrade { get; set; }
    }
}
